name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - 'github-pages/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Mover arquivos para a raiz
      - name: Move files to root
        run: |
          mkdir -p ./deploy
          cp -r ./github-pages/src/* ./deploy/

      # Passo 3: Listar arquivos no diretório do artefato (para depuração)
      - name: List files in artifact directory
        run: ls -R ./deploy

      # Passo 4: Carregar os arquivos para deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./deploy  # Agora os arquivos estão na raiz

      # Passo 5: Deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2