name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # Passo 1: Fazer checkout do código
      - name: Checkout do repositório
        uses: actions/checkout@v4

      # Passo 2: Listar arquivos na raiz (para depuração)
      - name: List files in root directory
        run: ls -R ./

      # Passo 3: Carregar os arquivos para deploy
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./  # Agora os arquivos estão na raiz

      # Passo 4: Deploy no GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2